import java.util.Scanner;

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2 , the first 10 terms will be:
                    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 143 ....

By considering the terms in the Fibonacci sequence whose values do not exceed N , find the sum of the even-valued terms.
Sample Input 0

2
10
100

Sample Output 0

10
44
Explanation 0

For N = 10 , we have (2,8) , sum is 10.
For N = 100, we have (2,8,34), sum is 44.
 */
public class EvenFibo {
    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);
        System.out.println("Enter Test Case : ");
        int t = in.nextInt();

        for(int i = 0; i < t; i++){
            System.out.println("Enter Num : ");
            long n = in.nextLong();

            long evenSum = 0;
            long a = 0;
            long b = 1;

            while(evenSum < n){
                long c = a+b;
                if(c > n)
                    break;
                if(c % 2 == 0)
                    evenSum += c;
                a = b;
                b = c;
            }
            System.out.println(evenSum);
        }
    }
}
